# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|
	  vb.memory = "4096"
	  vb.cpus = "2"
	  vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # Install Docker
  config.vm.provision :docker

  # Shell Provision  
  config.vm.provision "shell", privileged: false, path: "shell_provision/setup.sh"
  config.vm.provision "shell", privileged: false, path: "shell_provision/cluster_bootstrap.sh"

end
