# -*- mode: ruby -*-
# vi: set ft=ruby :

master_ip = "172.168.50.10"
num_workers = 2

Vagrant.configure("2") do |config|

  #config.vm.box = "bento/ubuntu-18.04"
  config.vm.box = "hashicorp/bionic64"

  config.vm.provision :shell, path: "shell_provision/vm_bootstrap.sh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.define "k8s-master", primary: true do |master|
    master.vm.network "private_network", ip: master_ip
    master.vm.hostname = "master"

    master.vm.provision :shell, path: "shell_provision/master_bootstrap.sh"
  end

  (1..num_workers).each do |i|
    config.vm.define "k8s-worker#{i}" do |node|
		worker_ip = master_ip.split('.').tap{|arr| arr[-1] = arr[-1].to_i + i}.join('.')
		
        node.vm.network "private_network", ip: worker_ip
        node.vm.hostname = "worker#{i}"
        
        node.vm.provision :shell, path: "shell_provision/worker_bootstrap.sh"
    end
  end

end
